# -*- coding: utf-8 -*-
"""31052025001

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kEg_QduTzoG7ySHxGgg8hvFqgFy30u8g
"""

#Example
x = int(input("Enter a number:"))

if x > 10:
  print("Above 10,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")
else:
  print("Below 10.")

#1. Is your number greater than 5?

#2. Is it your birthday AND are you 7 years old?

#3. What color is your balloon?

#4. Is the animal a dog or cat?

#5. Are you wearing red shirt and blue jeans?

#6. What number did you get on the test?

#7. Are you eating an apple and is it red?

#8. Is the number even or odd?

#9. What is your favorite color?

#10. What day is today?